name: Coverage Reports

on:
  push:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
          
      - name: Generate Coverage Reports
        run: |
          mvn clean verify
          mvn cobertura:cobertura
          
      - name: Get version
        run: echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
          
      - name: Deploy Coverage Reports
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: target/site/cobertura
          target-folder: cobertura/${{ env.VERSION }}
          branch: gh-pages