name: Pull Request Checks

on:
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Check Code Style
        run: mvn checkstyle:check
        
      - name: Run Tests with Coverage
        run: mvn verify
        
      - name: Check Coverage Threshold
        run: |
          COVERAGE=$(mvn jacoco:report | grep -A 1 "Total.*class" | grep "[0-9]\{1,3\}%" | cut -d" " -f2 | sed 's/%//g')
          if (( $(echo "$COVERAGE < 90" | bc -l) )); then
            echo "Test coverage is below 90% (Current: $COVERAGE%)"
            exit 1
          fi
          
      - name: Run Performance Tests
        run: mvn verify -P performance-tests
        
      - name: Run SAST with Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/java